### ISSUE TITLE
How are arguments supposed to be handled?

### ISSUE THREAD

**Issue by pboling** [AlexWayfer/alt_memery#93]
Is all of this expected, intentional?  Just want to manage my expectations when using the library.
```
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'alt_memery', require: false
end

require "memery"

class A
  include Memery

  memoize def call(time = Time.now)
      puts "called at #{time}"
      42
  end
end

a = A.new
puts "Call 1 (use default)"
a.call
puts "Call 1 (use default) Done\n\n"
sleep(1)
puts "Call 2 (use default)"
a.call
puts "Call 2 (use default) Done\n\n"
sleep(1)
puts "Call 3 (Time.now)"
a.call(Time.now)
puts "Call 3 (Time.now) Done\n\n"
sleep(1)
puts "Call 4 (Time.now 2nd)"
a.call(Time.now)
puts "Call 4 (Time.now 2nd) Done\n\n"
sleep(1)
puts "Call 5 (Time.new(2002))"
a.call(Time.new(2002, 10, 31, 2, 2, 2, "+02:00"))
puts "Call 5 (Time.new(2002)) Done\n\n"
sleep(1)
puts "Call 6 (Time.new(2002) 2nd)"
a.call(Time.new(2002, 10, 31, 2, 2, 2, "+02:00"))
puts "Call 6 (Time.new(2002) 2nd) Done\n\n"

```

And here's the output:
```
Call 1 (use default)
called at 2024-01-12 17:23:48 +0700
Call 1 (use default) Done

Call 2 (use default)
Call 2 (use default) Done

Call 3 (Time.now)
called at 2024-01-12 17:23:50 +0700
Call 3 (Time.now) Done

Call 4 (Time.now 2nd)
called at 2024-01-12 17:23:51 +0700
Call 4 (Time.now 2nd) Done

Call 5 (Time.new(2002))
called at 2002-10-31 02:02:02 +0200
Call 5 (Time.new(2002)) Done

Call 6 (Time.new(2002) 2nd)
Call 6 (Time.new(2002) 2nd) Done
```

To summarize...

The following calls w/ arguments are memoized, such that when called again they are not re-executed:

1. Default argument value is `Time.now`, which normally in Ruby is evaluated fresh on every call, but with memoization it is not.  This is the same behavior as some other memoization libraries, and maybe it has to be this way...
```
a.call
```
2. When the Time argument is representing the same time as a previous call, the memoized result is used.  This is cool.
```
a.call(Time.new(2002, 10, 31, 2, 2, 2, "+02:00"))
```

The following calls w/ arguments are **not** memoized, such that when called again they are freshly executed each time called:
```
a.call(Time.now)
```

Tested on Ruby 3.2.2

ref: https://stackoverflow.com/questions/53783291/ruby-default-arguments-static-or-dynamic

**Comment by AlexWayfer** [comment]
I guess, it's supposed to be so.

The memoization mechanism is pretty simple. As you can know, you can't have multiple methods in Ruby with the same name, but different arguments. So, the method name is the key.

Then… yes, you can have call-time-execution defaults in Ruby, even `begin-end` blocks or other methods call. But from a library it's pretty difficult to detect, analyze, etc. Simply available info is just number of arguments, their names, optionality, but not default values, even static ones:

```ruby
pry: #<A:0x00007fe9792ed848> > original_method.inspect
=> "#<UnboundMethod: A#call(time=...) .test.rb:10>"
pry: #<A:0x00007fe9792ed848> > original_method.parameters
=> [[:opt, :time]]
pry: #<A:0x00007fe9792ed848> > original_method.source_location
=> [".test.rb", 10]
```

So… the single way to analyze which I see — it's literally read the source code of the method, parse it, etc.
I don't think it's worth it.

You just should keep it in your head and know, how and when memoize methods. Probably, take out some logic in a separate method for memoization, or move default value inside the method, etc.

**Comment by pboling** [comment]
Thanks!  Very helpful.
