### ISSUE TITLE
Memoize methods with ActiveRecord objects as parameters

### ISSUE THREAD

**Issue by pboling** [AlexWayfer/alt_memery#96]
After #93 I assumed I understood how it would behave when memoizing methods with parameters that are complex objects (like the Time objects in that example).  My hope that that it would follow the same "identity" comparison that Rails uses to know that two ActiveRecord objects are the same, but that is not the case, as the methods are called repeatedly with the same object being passed every time.

Going to poke around in the source code for a while to look for an easy way to hack a solution.

**Comment by pboling** [comment]
Figured out the issue.  Memoization doesn't work with `module_function` methods.  For memoization to work the module can use `extend self` instead.

I tested various memoization libraries, and they all exhibited the same behavior.  If you can get `alt_memery` working with `module_function` then 🙇 🙇 🙇

**Comment by AlexWayfer** [comment]
Honestly, I had problems with `module_function` methods. I don't remember exactly, many years ago, but I've created [`module_methods`](https://github.com/AlexWayfer/module_methods) gem. You can be interested in this.

**Comment by pboling** [comment]
@AlexWayfer Thanks that gem may help me add Ruby 3 compat to my unobtrusive [debug_logging](https://github.com/pboling/debug_logging) gem!
